@extends('layouts.app', ['seoTitle' => $article->meta_title ?: $article->title.' — MCCG', 'seoDescription' => $article->meta_description ?: $article->excerpt, 'seoImage' => $article->featured_image ? asset('storage/'.$article->featured_image) : null, 'seoKeywords' => $article->keywords, 'ogType' => 'article'])
@push('structured-data')
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Article','headline'=>$article->title,'description'=>$article->excerpt,'datePublished'=>$article->published_at?->toIso8601String(),'dateModified'=>$article->updated_at->toIso8601String(),'author'=>['@type'=>'Organization','name'=>'MCCG'],'publisher'=>['@type'=>'Organization','name'=>'MCCG']], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
@endpush
@section('content')
<article><header class="border-b border-slate-200 bg-white py-14 sm:py-20"><div class="container-site max-w-4xl"><div class="mb-5 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs uppercase tracking-wider text-slate-400 sm:mb-6"><span class="font-semibold text-coral">{{ $article->category?->name }}</span><span>—</span><time>{{ $article->published_at?->translatedFormat('d F Y') }}</time></div><h1 class="break-words font-heading text-3xl font-bold leading-tight text-charcoal sm:text-4xl lg:text-5xl">{{ $article->title }}</h1><p class="mt-5 max-w-3xl text-base leading-7 text-slate-600 sm:mt-6 sm:text-lg sm:leading-8">{{ $article->excerpt }}</p></div></header>
@if($article->featured_image)<div class="container-site mt-8 max-w-5xl sm:-mb-8 sm:mt-10"><img src="{{ asset('storage/'.$article->featured_image) }}" alt="{{ $article->title }}" class="aspect-[16/9] w-full rounded-xl object-cover sm:aspect-[16/8] sm:rounded-none"></div>@endif
<div class="container-site grid max-w-5xl gap-8 py-12 sm:gap-12 sm:py-16 lg:grid-cols-[minmax(0,1fr)_190px]"><div class="prose-mccg min-w-0">{!! $article->content !!}</div><aside class="order-first lg:order-last"><div class="rounded-r-lg border-l-2 border-coral bg-white p-5 text-sm"><p class="font-semibold text-charcoal">Publié par</p><p class="mt-1">{{ $article->author?->name ?? 'Équipe MCCG' }}</p><a href="{{ route('contact') }}" class="mt-4 inline-flex min-h-11 items-center font-semibold text-coral sm:mt-5">Une question ? →</a></div></aside></div></article>
@if($related->isNotEmpty())<section class="border-t border-slate-200 section-space"><div class="container-site"><h2 class="section-title mb-8 sm:mb-10">À lire également</h2><div class="grid gap-6 md:grid-cols-2 lg:grid-cols-3" data-stagger>@foreach($related as $item)<x-article-card :article="$item" />@endforeach</div></div></section>@endif
@endsection
