@extends('layouts.app', ['seoTitle' => $article->meta_title ?: $article->title.' — MCCG', 'seoDescription' => $article->meta_description ?: $article->excerpt, 'seoImage' => $article->featured_image ? asset('storage/'.$article->featured_image) : null, 'seoKeywords' => $article->keywords, 'ogType' => 'article'])
@push('structured-data')
<script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'Article','headline'=>$article->title,'description'=>$article->excerpt,'datePublished'=>$article->published_at?->toIso8601String(),'dateModified'=>$article->updated_at->toIso8601String(),'author'=>['@type'=>'Organization','name'=>'MCCG'],'publisher'=>['@type'=>'Organization','name'=>'MCCG']], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
@endpush
@section('content')
<article><header class="border-b border-slate-200 bg-white py-20"><div class="container-site max-w-4xl"><div class="mb-6 flex gap-3 text-xs uppercase tracking-wider text-slate-400"><span class="font-semibold text-coral">{{ $article->category?->name }}</span><span>—</span><time>{{ $article->published_at?->translatedFormat('d F Y') }}</time></div><h1 class="font-heading text-4xl font-bold leading-tight text-charcoal sm:text-5xl">{{ $article->title }}</h1><p class="mt-6 max-w-3xl text-lg leading-8 text-slate-600">{{ $article->excerpt }}</p></div></header>
@if($article->featured_image)<div class="container-site -mb-8 mt-10 max-w-5xl"><img src="{{ asset('storage/'.$article->featured_image) }}" alt="{{ $article->title }}" class="aspect-[16/8] w-full object-cover"></div>@endif
<div class="container-site grid max-w-5xl gap-12 py-16 lg:grid-cols-[1fr_190px]"><div class="prose-mccg">{!! $article->content !!}</div><aside class="order-first lg:order-last"><div class="rounded-r-lg border-l-2 border-coral bg-white p-5 text-sm"><p class="font-semibold text-charcoal">Publié par</p><p class="mt-1">{{ $article->author?->name ?? 'Équipe MCCG' }}</p><a href="{{ route('contact') }}" class="mt-5 inline-block font-semibold text-coral">Une question ? →</a></div></aside></div></article>
@if($related->isNotEmpty())<section class="border-t border-slate-200 section-space"><div class="container-site"><h2 class="section-title mb-10">À lire également</h2><div class="grid gap-6 md:grid-cols-3" data-stagger>@foreach($related as $item)<x-article-card :article="$item" />@endforeach</div></div></section>@endif
@endsection
